# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b878514e2d6b235718a15bb2ee9a1604a6cca81c202917aad29dd8b1755afe359f41ca49a62223d1d565b5829351b8b9de85c629d31e0cbe4b51e59fc6208dd

test:
  secret_key_base: cdb0621ac3938cda384d5aaf624f2acd36f675eceadc6583bf8bc80fa461c4bfb41a4de27e3a05e6d2deba74ae088e47edade04c928bc5e18678fc03db2fa00d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
